name: Github Actions Demo 4
on:
  push:
    branches: [main]
    paths-ignore:  [.github/**]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "🎉 The job was triggered by event: ${{ github.event_name }}"
        echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

    - uses: actions/checkout@v3.3.0

    - name: List files in the repository
      run: |
        echo "The repository ${{ github.repository }} contains the following files:"
        tree
  Unit-Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - run: echo "🧪 Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - run: |
          echo "🧪 Testing..."
          sleep 15
  Production:
    runs-on: ubuntu-latest
    needs: [Unit-Test, Load-Test]
    environment:
      name: Production
      url: https://bouvet.no
    steps:
      - run: |
          echo "🚀 Step 1..."
          sleep 2
      - run: |
          echo "🚀 Step 2..."
          sleep 2
      - run: |
          echo "🚀 Step 3..."
          sleep 2
      - run: |
          echo "🚀 Step 4..."
          sleep 2
      - run: |
          echo "🚀 Step 5..."
          sleep 2
  
